name: Sync All Repos to Gitee

on:
  schedule:
    - cron: '0 3 * * *'  # 每天凌晨3点运行
  workflow_dispatch:  # 允许手动触发

jobs:
  sync-repos:
    runs-on: ubuntu-latest

    env:
      TOKEN: ${{ secrets.TOKEN }}
      GITEE_ACCESS_TOKEN: ${{ secrets.GITEE_ACCESS_TOKEN }}
      REPOS_TO_SYNC: ${{ secrets.REPOS_TO_SYNC }}
      JQ_VERSION: 1.6
      JQ_URL: https://github.com/stedolan/jq/releases/download/jq-$JQ_VERSION/jq-linux64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install jq
        run: |
          wget ${{ env.JQ_URL }} -O /usr/local/bin/jq
          chmod +x /usr/local/bin/jq

      - name: Sync repositories
        run: |
          echo "$REPOS_TO_SYNC" | jq -r '.[] | "\(.github_repo) \(.gitee_repo)"' | while read -r line; do
            IFS=' ' read -r github_repo gitee_repo <<< "$line"
            echo "Syncing $github_repo to $gitee_repo"

            # Clone the GitHub repository
            git clone https://github.com/$github_repo.git

            repo_name=$(basename $github_repo)
            cd $repo_name

            # Add Gitee as a remote
            git remote add gitee https://$GITEE_ACCESS_TOKEN:x-oauth-basic@gitee.com/$gitee_repo.git

            # Debugging: Print the Gitee remote URL
            echo "Gitee remote URL: $(git config --get remote.gitee.url)"

            # Fetch all branches and tags
            git fetch --all

            # Push all branches and tags to Gitee
            git push gitee --all
            git push gitee --tags

            cd ..
            rm -rf $repo_name
          done
        shell: bash
